package com.isands.farmer.registry.model.impl;

import com.isands.farmer.registry.model.Farmer;
import com.isands.farmer.registry.model.FarmerModel;
import com.isands.farmer.registry.model.FarmerSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Farmer service. Represents a row in the &quot;FarmerRegistry_Farmer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.isands.farmer.registry.model.FarmerModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FarmerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FarmerImpl
 * @see com.isands.farmer.registry.model.Farmer
 * @see com.isands.farmer.registry.model.FarmerModel
 * @generated
 */
@JSON(strict = true)
public class FarmerModelImpl extends BaseModelImpl<Farmer>
    implements FarmerModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a farmer model instance should use the {@link com.isands.farmer.registry.model.Farmer} interface instead.
     */
    public static final String TABLE_NAME = "FarmerRegistry_Farmer";
    public static final Object[][] TABLE_COLUMNS = {
            { "id_", Types.BIGINT },
            { "organizationName", Types.VARCHAR },
            { "legalFormId", Types.INTEGER },
            { "inn", Types.VARCHAR },
            { "kpp", Types.VARCHAR },
            { "ogrn", Types.VARCHAR },
            { "regionId", Types.BIGINT },
            { "registrationDate", Types.TIMESTAMP },
            { "archive", Types.BOOLEAN }
        };
    public static final String TABLE_SQL_CREATE = "create table FarmerRegistry_Farmer (id_ LONG not null primary key,organizationName VARCHAR(75) null,legalFormId INTEGER,inn VARCHAR(75) null,kpp VARCHAR(75) null,ogrn VARCHAR(75) null,regionId LONG,registrationDate DATE null,archive BOOLEAN)";
    public static final String TABLE_SQL_DROP = "drop table FarmerRegistry_Farmer";
    public static final String ORDER_BY_JPQL = " ORDER BY farmer.registrationDate DESC, farmer.id DESC";
    public static final String ORDER_BY_SQL = " ORDER BY FarmerRegistry_Farmer.registrationDate DESC, FarmerRegistry_Farmer.id_ DESC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.isands.farmer.registry.model.Farmer"),
            false);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.isands.farmer.registry.model.Farmer"),
            false);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.isands.farmer.registry.model.Farmer"),
            true);
    public static long ARCHIVE_COLUMN_BITMASK = 1L;
    public static long ID_COLUMN_BITMASK = 2L;
    public static long INN_COLUMN_BITMASK = 4L;
    public static long ORGANIZATIONNAME_COLUMN_BITMASK = 8L;
    public static long REGIONID_COLUMN_BITMASK = 16L;
    public static long REGISTRATIONDATE_COLUMN_BITMASK = 32L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.isands.farmer.registry.model.Farmer"));
    private static ClassLoader _classLoader = Farmer.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] { Farmer.class };
    private long _id;
    private long _originalId;
    private boolean _setOriginalId;
    private String _organizationName;
    private String _originalOrganizationName;
    private int _legalFormId;
    private String _inn;
    private String _originalInn;
    private String _kpp;
    private String _ogrn;
    private long _regionId;
    private long _originalRegionId;
    private boolean _setOriginalRegionId;
    private Date _registrationDate;
    private Date _originalRegistrationDate;
    private boolean _archive;
    private boolean _originalArchive;
    private boolean _setOriginalArchive;
    private long _columnBitmask;
    private Farmer _escapedModel;

    public FarmerModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Farmer toModel(FarmerSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Farmer model = new FarmerImpl();

        model.setId(soapModel.getId());
        model.setOrganizationName(soapModel.getOrganizationName());
        model.setLegalFormId(soapModel.getLegalFormId());
        model.setInn(soapModel.getInn());
        model.setKpp(soapModel.getKpp());
        model.setOgrn(soapModel.getOgrn());
        model.setRegionId(soapModel.getRegionId());
        model.setRegistrationDate(soapModel.getRegistrationDate());
        model.setArchive(soapModel.getArchive());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Farmer> toModels(FarmerSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Farmer> models = new ArrayList<Farmer>(soapModels.length);

        for (FarmerSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _id;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Farmer.class;
    }

    @Override
    public String getModelClassName() {
        return Farmer.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("id", getId());
        attributes.put("organizationName", getOrganizationName());
        attributes.put("legalFormId", getLegalFormId());
        attributes.put("inn", getInn());
        attributes.put("kpp", getKpp());
        attributes.put("ogrn", getOgrn());
        attributes.put("regionId", getRegionId());
        attributes.put("registrationDate", getRegistrationDate());
        attributes.put("archive", getArchive());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long id = (Long) attributes.get("id");

        if (id != null) {
            setId(id);
        }

        String organizationName = (String) attributes.get("organizationName");

        if (organizationName != null) {
            setOrganizationName(organizationName);
        }

        Integer legalFormId = (Integer) attributes.get("legalFormId");

        if (legalFormId != null) {
            setLegalFormId(legalFormId);
        }

        String inn = (String) attributes.get("inn");

        if (inn != null) {
            setInn(inn);
        }

        String kpp = (String) attributes.get("kpp");

        if (kpp != null) {
            setKpp(kpp);
        }

        String ogrn = (String) attributes.get("ogrn");

        if (ogrn != null) {
            setOgrn(ogrn);
        }

        Long regionId = (Long) attributes.get("regionId");

        if (regionId != null) {
            setRegionId(regionId);
        }

        Date registrationDate = (Date) attributes.get("registrationDate");

        if (registrationDate != null) {
            setRegistrationDate(registrationDate);
        }

        Boolean archive = (Boolean) attributes.get("archive");

        if (archive != null) {
            setArchive(archive);
        }
    }

    @JSON
    @Override
    public long getId() {
        return _id;
    }

    @Override
    public void setId(long id) {
        _columnBitmask = -1L;

        if (!_setOriginalId) {
            _setOriginalId = true;

            _originalId = _id;
        }

        _id = id;
    }

    public long getOriginalId() {
        return _originalId;
    }

    @JSON
    @Override
    public String getOrganizationName() {
        if (_organizationName == null) {
            return StringPool.BLANK;
        } else {
            return _organizationName;
        }
    }

    @Override
    public void setOrganizationName(String organizationName) {
        _columnBitmask |= ORGANIZATIONNAME_COLUMN_BITMASK;

        if (_originalOrganizationName == null) {
            _originalOrganizationName = _organizationName;
        }

        _organizationName = organizationName;
    }

    public String getOriginalOrganizationName() {
        return GetterUtil.getString(_originalOrganizationName);
    }

    @JSON
    @Override
    public int getLegalFormId() {
        return _legalFormId;
    }

    @Override
    public void setLegalFormId(int legalFormId) {
        _legalFormId = legalFormId;
    }

    @JSON
    @Override
    public String getInn() {
        if (_inn == null) {
            return StringPool.BLANK;
        } else {
            return _inn;
        }
    }

    @Override
    public void setInn(String inn) {
        _columnBitmask |= INN_COLUMN_BITMASK;

        if (_originalInn == null) {
            _originalInn = _inn;
        }

        _inn = inn;
    }

    public String getOriginalInn() {
        return GetterUtil.getString(_originalInn);
    }

    @JSON
    @Override
    public String getKpp() {
        if (_kpp == null) {
            return StringPool.BLANK;
        } else {
            return _kpp;
        }
    }

    @Override
    public void setKpp(String kpp) {
        _kpp = kpp;
    }

    @JSON
    @Override
    public String getOgrn() {
        if (_ogrn == null) {
            return StringPool.BLANK;
        } else {
            return _ogrn;
        }
    }

    @Override
    public void setOgrn(String ogrn) {
        _ogrn = ogrn;
    }

    @JSON
    @Override
    public long getRegionId() {
        return _regionId;
    }

    @Override
    public void setRegionId(long regionId) {
        _columnBitmask |= REGIONID_COLUMN_BITMASK;

        if (!_setOriginalRegionId) {
            _setOriginalRegionId = true;

            _originalRegionId = _regionId;
        }

        _regionId = regionId;
    }

    public long getOriginalRegionId() {
        return _originalRegionId;
    }

    @JSON
    @Override
    public Date getRegistrationDate() {
        return _registrationDate;
    }

    @Override
    public void setRegistrationDate(Date registrationDate) {
        _columnBitmask = -1L;

        if (_originalRegistrationDate == null) {
            _originalRegistrationDate = _registrationDate;
        }

        _registrationDate = registrationDate;
    }

    public Date getOriginalRegistrationDate() {
        return _originalRegistrationDate;
    }

    @JSON
    @Override
    public boolean getArchive() {
        return _archive;
    }

    @Override
    public boolean isArchive() {
        return _archive;
    }

    @Override
    public void setArchive(boolean archive) {
        _columnBitmask |= ARCHIVE_COLUMN_BITMASK;

        if (!_setOriginalArchive) {
            _setOriginalArchive = true;

            _originalArchive = _archive;
        }

        _archive = archive;
    }

    public boolean getOriginalArchive() {
        return _originalArchive;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            Farmer.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Farmer toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Farmer) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        FarmerImpl farmerImpl = new FarmerImpl();

        farmerImpl.setId(getId());
        farmerImpl.setOrganizationName(getOrganizationName());
        farmerImpl.setLegalFormId(getLegalFormId());
        farmerImpl.setInn(getInn());
        farmerImpl.setKpp(getKpp());
        farmerImpl.setOgrn(getOgrn());
        farmerImpl.setRegionId(getRegionId());
        farmerImpl.setRegistrationDate(getRegistrationDate());
        farmerImpl.setArchive(getArchive());

        farmerImpl.resetOriginalValues();

        return farmerImpl;
    }

    @Override
    public int compareTo(Farmer farmer) {
        int value = 0;

        value = DateUtil.compareTo(getRegistrationDate(),
                farmer.getRegistrationDate());

        value = value * -1;

        if (value != 0) {
            return value;
        }

        if (getId() < farmer.getId()) {
            value = -1;
        } else if (getId() > farmer.getId()) {
            value = 1;
        } else {
            value = 0;
        }

        value = value * -1;

        if (value != 0) {
            return value;
        }

        return 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Farmer)) {
            return false;
        }

        Farmer farmer = (Farmer) obj;

        long primaryKey = farmer.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        FarmerModelImpl farmerModelImpl = this;

        farmerModelImpl._originalId = farmerModelImpl._id;

        farmerModelImpl._setOriginalId = false;

        farmerModelImpl._originalOrganizationName = farmerModelImpl._organizationName;

        farmerModelImpl._originalInn = farmerModelImpl._inn;

        farmerModelImpl._originalRegionId = farmerModelImpl._regionId;

        farmerModelImpl._setOriginalRegionId = false;

        farmerModelImpl._originalRegistrationDate = farmerModelImpl._registrationDate;

        farmerModelImpl._originalArchive = farmerModelImpl._archive;

        farmerModelImpl._setOriginalArchive = false;

        farmerModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Farmer> toCacheModel() {
        FarmerCacheModel farmerCacheModel = new FarmerCacheModel();

        farmerCacheModel.id = getId();

        farmerCacheModel.organizationName = getOrganizationName();

        String organizationName = farmerCacheModel.organizationName;

        if ((organizationName != null) && (organizationName.length() == 0)) {
            farmerCacheModel.organizationName = null;
        }

        farmerCacheModel.legalFormId = getLegalFormId();

        farmerCacheModel.inn = getInn();

        String inn = farmerCacheModel.inn;

        if ((inn != null) && (inn.length() == 0)) {
            farmerCacheModel.inn = null;
        }

        farmerCacheModel.kpp = getKpp();

        String kpp = farmerCacheModel.kpp;

        if ((kpp != null) && (kpp.length() == 0)) {
            farmerCacheModel.kpp = null;
        }

        farmerCacheModel.ogrn = getOgrn();

        String ogrn = farmerCacheModel.ogrn;

        if ((ogrn != null) && (ogrn.length() == 0)) {
            farmerCacheModel.ogrn = null;
        }

        farmerCacheModel.regionId = getRegionId();

        Date registrationDate = getRegistrationDate();

        if (registrationDate != null) {
            farmerCacheModel.registrationDate = registrationDate.getTime();
        } else {
            farmerCacheModel.registrationDate = Long.MIN_VALUE;
        }

        farmerCacheModel.archive = getArchive();

        return farmerCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(19);

        sb.append("{id=");
        sb.append(getId());
        sb.append(", organizationName=");
        sb.append(getOrganizationName());
        sb.append(", legalFormId=");
        sb.append(getLegalFormId());
        sb.append(", inn=");
        sb.append(getInn());
        sb.append(", kpp=");
        sb.append(getKpp());
        sb.append(", ogrn=");
        sb.append(getOgrn());
        sb.append(", regionId=");
        sb.append(getRegionId());
        sb.append(", registrationDate=");
        sb.append(getRegistrationDate());
        sb.append(", archive=");
        sb.append(getArchive());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(31);

        sb.append("<model><model-name>");
        sb.append("com.isands.farmer.registry.model.Farmer");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id</column-name><column-value><![CDATA[");
        sb.append(getId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>organizationName</column-name><column-value><![CDATA[");
        sb.append(getOrganizationName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>legalFormId</column-name><column-value><![CDATA[");
        sb.append(getLegalFormId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>inn</column-name><column-value><![CDATA[");
        sb.append(getInn());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>kpp</column-name><column-value><![CDATA[");
        sb.append(getKpp());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>ogrn</column-name><column-value><![CDATA[");
        sb.append(getOgrn());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>regionId</column-name><column-value><![CDATA[");
        sb.append(getRegionId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>registrationDate</column-name><column-value><![CDATA[");
        sb.append(getRegistrationDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>archive</column-name><column-value><![CDATA[");
        sb.append(getArchive());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
