package com.isands.farmer.registry.model.impl;

import com.isands.farmer.registry.model.LegalForm;
import com.isands.farmer.registry.service.LegalFormLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the LegalForm service. Represents a row in the &quot;FarmerRegistry_LegalForm&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LegalFormImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LegalFormImpl
 * @see com.isands.farmer.registry.model.LegalForm
 * @generated
 */
public abstract class LegalFormBaseImpl extends LegalFormModelImpl
    implements LegalForm {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a legal form model instance should use the {@link LegalForm} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            LegalFormLocalServiceUtil.addLegalForm(this);
        } else {
            LegalFormLocalServiceUtil.updateLegalForm(this);
        }
    }
}
