package com.isands.farmer.registry.model;

import com.isands.farmer.registry.service.persistence.RefPK;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Ref service. Represents a row in the &quot;FarmerRegistry_Ref&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.isands.farmer.registry.model.impl.RefModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.isands.farmer.registry.model.impl.RefImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Ref
 * @see com.isands.farmer.registry.model.impl.RefImpl
 * @see com.isands.farmer.registry.model.impl.RefModelImpl
 * @generated
 */
public interface RefModel extends BaseModel<Ref> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a ref model instance should use the {@link Ref} interface instead.
     */

    /**
     * Returns the primary key of this ref.
     *
     * @return the primary key of this ref
     */
    public RefPK getPrimaryKey();

    /**
     * Sets the primary key of this ref.
     *
     * @param primaryKey the primary key of this ref
     */
    public void setPrimaryKey(RefPK primaryKey);

    /**
     * Returns the farmer ID of this ref.
     *
     * @return the farmer ID of this ref
     */
    public long getFarmerId();

    /**
     * Sets the farmer ID of this ref.
     *
     * @param farmerId the farmer ID of this ref
     */
    public void setFarmerId(long farmerId);

    /**
     * Returns the region ID of this ref.
     *
     * @return the region ID of this ref
     */
    public long getRegionId();

    /**
     * Sets the region ID of this ref.
     *
     * @param regionId the region ID of this ref
     */
    public void setRegionId(long regionId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.isands.farmer.registry.model.Ref ref);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.isands.farmer.registry.model.Ref> toCacheModel();

    @Override
    public com.isands.farmer.registry.model.Ref toEscapedModel();

    @Override
    public com.isands.farmer.registry.model.Ref toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
